version: '3.8'

services:
  python:
    container_name: face-verification
    build:
      context: ../../../
      dockerfile_inline: |
        FROM python:3.9-slim

        WORKDIR /app

        # Update pip first
        RUN pip install --upgrade pip

        # Install system dependencies
        RUN apt-get update && apt-get install -y \
            build-essential \
            cmake \
            libgl1 \
            libglib2.0-0 \
            libglib2.0-dev \
            libgtk-3-dev \
            libavcodec-dev \
            libavformat-dev \
            libswscale-dev \
            && rm -rf /var/lib/apt/lists/*

        # Install compatible versions that work well together
        RUN pip install --no-cache-dir \
            fastapi==0.104.1 \
            uvicorn[standard]==0.24.0 \
            tensorflow==2.13.0 \
            keras==2.13.1 \
            numpy==1.24.3 \
            opencv-python==4.8.1.78 \
            pillow==10.0.1 \
            pandas==2.0.3 \
            deepface==0.0.79

        # Copy the Python script
        COPY src/main/python/scripts/verify_face_match.py /app/

        EXPOSE 8000

        CMD ["uvicorn", "verify_face_match:app", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - '8000:8000'
    restart: unless-stopped
